<script lang="ts">
	import '../styles/global.scss';
	import { closeNav, navOpened } from '$lib/store';
	import Header from '../partials/header.svelte';
	import Nav from '../partials/nav.svelte';
	import { browser } from '$app/environment';

	const META_DESCRIPTION =
		'Odkryj nowoczesne i komfortowe domki 6-osobowe w Black Sarbinowo, położone w urokliwej nadmorskiej miejscowości. Zarezerwuj swój spokojny wypoczynek już dziś!' as const;
	const META_IMAGE_URL = 'https://www.domki-black.pl/domki.jpg' as const;
	const META_URL = 'https://www.domki-black.pl' as const;

	navOpened.subscribe((value) => {
		if (browser) document.body.classList.toggle('noscroll', value);
	});
</script>

<svelte:head>
	<title>Domki letniskowe - Sarbinowo "Black"</title>
	<meta name="description" content={META_DESCRIPTION} />
	<link rel="canonical" href={META_URL} />

	<meta property="og:title" content="Black Sarbinowo" />
	<meta property="og:description" content={META_DESCRIPTION} />
	<meta property="og:type" content="website" />
	<meta property="og:url" content={META_URL} />
	<meta property="og:image" content={META_IMAGE_URL} />

	<meta name="twitter:card" content="summary_large_image" />
	<meta name="twitter:title" content="Black Sarbinowo" />
	<meta name="twitter:description" content={META_DESCRIPTION} />
	<meta name="twitter:image" content={META_IMAGE_URL} />

	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	{@html `<script type="application/ld+json">
			{
				"@context": "http://schema.org",
				"@type": "LocalBusiness",
				"name": "Domki Black Sarbinowo",
				"priceRange": "$$",
				"url": ${JSON.stringify(META_URL)},
				"image": ${JSON.stringify(META_IMAGE_URL)},
				"telephone": "+48508101504",
				"email": "black.sarbinowo@gmail.com",
				"address": {
					"@type": "PostalAddress",
					"streetAddress": "Wrzosowa 6",
					"addressLocality": "Sarbinowo",
					"addressCountry": "pl",
					"postalCode": "76-034"
				},
				"sameAs": [
					"https://www.facebook.com/BlackSarbinowo/", 
					"https://www.instagram.com/domki.black/", 
					"https://www.nocowanie.pl/noclegi/sarbinowo/domki/163718/", 
					"https://www.e-wczasy.pl/noclegi/sarbinowo/domki/black-sarbinowo,13591", 
					"https://meteor-turystyka.pl/black-sarbinowo,sarbinowo.html", 
					"https://www.restugo.com/pl/domkiblacksarbinowo"
				]
			}
	</script>`}
</svelte:head>

<Header />
<div class="pusher-wrapper">
	<Nav />
	<div class="pusher" class:active={$navOpened}>
		<button class="overlay" on:click={closeNav} class:active={$navOpened} tabindex="-1" />
		<slot />
	</div>
</div>
